import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "./components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
          <header className="p-4 bg-slate-900 text-white text-center">
            {/* <p>Welcome to Next 15 Crash</p> */}
            <Navigation />
          </header>
          {children}
          <footer className="p-4 bg-gray-900 text-white text-center">
            <p>© {new Date().getFullYear()} Next 15 Crash</p>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
